In [ ]:
%%html
<style>
.h1_cell, .just_text {
    box-sizing: border-box;
    padding-top:5px;
    padding-bottom:5px;
    font-family: "Times New Roman", Georgia, Serif;
    font-size: 125%;
    line-height: 22px; /* 5px +12px + 5px */
    text-indent: 25px;
    background-color: #fbfbea;
    padding: 10px;
}
.code_block {
    box-sizing: border-box;
    padding-top:5px;
    padding-bottom:5px;
    font-size: 75%;
    line-height: 22px; /* 5px +12px + 5px */
    #text-indent: 25px;
    #background-color: #fbfbea;
    padding: 5px;
}

hr { 
    display: block;
    margin-top: 0.5em;
    margin-bottom: 0.5em;
    margin-left: auto;
    margin-right: auto;
    border-style: inset;
    border-width: 2px;
}
</style>

<h1>
<center>
Download and Installation
</center>
</h1>

In [1]:
import requests
import os
import sys
import subprocess

<div class=h1_cell>
<p>
Download the spark tarball in the current directory. The URL is one of many mirrors listed on spark's official website.
</div>

In [ ]:
spark_url = "http://apache.osuosl.org/spark/spark-2.3.0/spark-2.3.0-bin-hadoop2.7.tgz"
r = requests.get(spark_url, stream=True)
filename = spark_url.rsplit('/')[-1]
with open(filename, 'wb') as f:
    f.write(r.content)

<div class=h1_cell>
<p>
Extract the spark tarball in the 'spark/' directory.
</div>

In [ ]:
subprocess.call('mkdir spark'.split(' '))
subprocess.call('tar -xf spark-2.3.0-bin-hadoop2.7.tgz -C spark --strip-components 1'.split(' '))

<div class=h1_cell>
<p>
Add spark_home environment variable.
<p>
Add spark_home + '/bin' to run a pyspark console.
<p>
Add spark_home + '/python*' to environment to import pyspark.
</div>

In [2]:
os.environ['SPARK_HOME'] = os.environ['HOME'] + '/spark'
os.environ['PATH'] += ':' + os.environ['SPARK_HOME'] + '/bin'
sys.path.append(os.environ['SPARK_HOME'] + '/python')
sys.path.append(os.environ['SPARK_HOME'] + '/python/lib/py4j-0.10.6-src.zip')

<div class=h1_cell>
<p>
Write the names of the slave nodes in the cluster. This script currently assumes the master machine is blue0.
</div>

In [ ]:
machines = ["blue1", "blue3"]
content = "\n".join(machines)
with open(os.environ['SPARK_HOME'] + "/conf/slaves", 'w') as f:
    f.write(content)

<div class=h1_cell>
<p>
We now need to do the same exact thing on all the slave nodes. We will:
<ul>
<li>
Convert this notebook to a python file.
<li>
Delete the lines after the comment in the code below.
<li>
Run the editted python script on each slave node.
</ul>
<p>
Note: These nodes must have password-less ssh tunneling configured.
</div>

In [ ]:
# Convert this ipython notebook to python script
!jupyter nbconvert --to=python setup_spark.ipynb

In [ ]:
read_file = open('setup_spark.py', 'r')
lines = read_file.readlines()
read_file.close()
with open('setup_spark.py', 'w') as f:
    i = 0
    while i < len(lines) and lines[i].strip() != '# Convert this ipython notebook to python script':
        f.write(lines[i])
        i += 1

<div class=h1_cell>
<p>
This will take awhile. For each node, the script is downloading spark, extracting the package and configuring the environment.
</div>

In [ ]:
!ssh blue1 python < setup_spark.py
!ssh blue3 python < setup_spark.py

<h1>
<center>
Using PySpark
</center>
</h1>

<div class=h1_cell>
<p>
Start the cluster.
</div>

In [3]:
# run start-all.sh
subprocess.call(os.environ['SPARK_HOME'] + "/sbin/start-all.sh", env=os.environ)

0

<div class=h1_cell>
<p>
This is where most other programs regarding this project will start.
</div>

In [4]:
from pyspark import SparkContext
from pyspark.sql import SparkSession
spark = SparkSession(SparkContext(master='spark://blue0:7077'))
spark

<div class=h1_cell>
<p>
Lets generate some semi-random data and run a Spark K-Means implementation on it. We'll create a 2D array with 4 centers.
</div>

In [5]:
# 4 clusters
from random import random, shuffle

upper_left = [[random()*0.5, random()*0.5 + 0.5] for _ in range(2500)]
upper_right = [[random()*0.5 + 0.5 for _ in range(2)] for _ in range(2500)]
bottom_left = [[random()*0.5 for _ in range(2)] for _ in range(2500)]
bottom_right = [[random()*.5 + 0.5, random()*0.5] for _ in range(2500)]

matrix = upper_left + upper_right + bottom_left + bottom_right
shuffle(matrix)

data = spark.createDataFrame(matrix, schema=["A", "B"])
data.show(5)

+-------------------+-------------------+
|                  A|                  B|
+-------------------+-------------------+
|0.37934741961671314|0.19842292770414172|
| 0.4827234474797606| 0.8368192843182927|
| 0.7645647616824591| 0.2901033322963689|
|0.04517736175807846| 0.2516191581625483|
| 0.0997401767803513| 0.8537358668875344|
+-------------------+-------------------+
only showing top 5 rows



In [6]:
from pyspark.ml.clustering import KMeans
from pyspark.ml.feature import VectorAssembler

vdf = VectorAssembler(inputCols=data.columns, outputCol="features").transform(data)
vdf.show(5)

+-------------------+-------------------+--------------------+
|                  A|                  B|            features|
+-------------------+-------------------+--------------------+
|0.37934741961671314|0.19842292770414172|[0.37934741961671...|
| 0.4827234474797606| 0.8368192843182927|[0.48272344747976...|
| 0.7645647616824591| 0.2901033322963689|[0.76456476168245...|
|0.04517736175807846| 0.2516191581625483|[0.04517736175807...|
| 0.0997401767803513| 0.8537358668875344|[0.09974017678035...|
+-------------------+-------------------+--------------------+
only showing top 5 rows



In [7]:
kmeans = KMeans(k=4, maxIter=10, initMode="random")
model = kmeans.fit(vdf)

wssse = model.computeCost(vdf)
print("Within Set Sum of Squared Errors = " + str(wssse))

print("Centers:")
model.clusterCenters()

Within Set Sum of Squared Errors = 416.826660058
Centers:


[array([ 0.26453331,  0.23473974]),
 array([ 0.23673167,  0.74518827]),
 array([ 0.7365823 ,  0.74851205]),
 array([ 0.76313915,  0.25215131])]

<div class=h1_cell>
<p>
You can compare this to a python-only single-machine k-means to get an idea of performance gain.
</div>

<h2>
<center>
Latent Semantic Analysis
</center>
</h2>

<div class=h1_cell>
<p>
We can look at all the words in a tweet dataset and determine which words may be related to each other, usually by topic.
</div>

In [8]:
# Spark doesn't do csv files very well, so we'll read the data into pandas
# Then we can pass it to spark
if(True):  # if on raspberry pi, change if otherwise
    subprocess.call('sudo apt-get install python-pandas'.split(' '))
else:
    subprocess.call('pip install pandas')

import pandas as pd
tweets = pd.read_csv("https://docs.google.com/spreadsheets/d/1tw90jUqTQoRt-RNOqNWronMN46y7dxb2ciQwj1YFsTo/export?format=csv")
tweets.head()

id  label                                              tweet
0   1      0  @user when a father is dysfunctional and is so...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty
3   4      0  #model   i love u take with u all the time in ...
4   5      0             factsguide: society now    #motivation

In [9]:
tweets.iloc[0]['tweet']

'@user when a father is dysfunctional and is so selfish he drags his kids into his dysfunction.   #run'

<div class=h1_cell>
<p>
We need to take each tweet, break it down into words and remove any unuseful words (stopwords)
</div>

In [10]:
!pip install nltk

from nltk.tokenize import WordPunctTokenizer
from nltk.corpus import stopwords
from nltk import download
from string import punctuation

word_punct_tokenizer = WordPunctTokenizer()
download('stopwords')
swords = stopwords.words('english')

def sentence_wrangler(sentence):
    word_list = word_punct_tokenizer.tokenize(sentence.lower())
    removed_words = []
    result = []
    for word in word_list:
        if word in swords:
            removed_words.append(word)
            continue
        check = False
        for char in word:
            if char in punctuation:
                check = True
                removed_words.append(word)
                break
        if not check: result.append(word)
      
    return result, removed_words

You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[nltk_data] Downloading package stopwords to /home/pi/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


<div class=h1_cell>
<p>
Create a set of all unique words. Then represent each tweet as a RowVector of words.
<p>
For example, the vector representing "Clippers down 2 points at the second half #NBAFinals" would have a 1 in each of the columns of the words in the tweet.
</div>

In [11]:
# Get tweets with no special characters (ascii)
bag = set()
sentences = []
for i in range(len(tweets.index[:100])):
    t = tweets.iloc[i]['tweet']
    try:
        t.encode('ascii')
        words = set(sentence_wrangler(t)[0])
        for word in words:
            if word not in bag:
                bag.add(word)
        sentences.append(words)
    except UnicodeDecodeError:
        pass
bag = frozenset(bag)
print(sentences[0])

set(['selfish', 'kids', 'run', 'father', 'drags', 'user', 'dysfunctional', 'dysfunction'])


In [12]:
all_words = list(bag)
occur_matrix = pd.DataFrame(columns=all_words)
zeros = [0]*len(bag)
for sentence in sentences:
    occur_matrix = occur_matrix.append(pd.DataFrame([zeros], columns=all_words), ignore_index=True)
    for word in sentence:
        occur_matrix.loc[len(occur_matrix.index)-1, word] = 1
occur_matrix.head()

shop  shot  show  tells  probe  ica16  leads  basilicabotanica  go  21st  \
0     0     0     0      0      0      0      0                 0   0     0   
1     0     0     0      0      0      0      0                 0   0     0   
2     0     0     0      0      0      0      0                 0   0     0   
3     0     0     0      0      0      0      0                 0   0     0   
4     0     0     0      0      0      0      0                 0   0     0   

   ...   hu  weekend  forever  calls  wife  sometimes  gr8  points  leak  \
0  ...    0        0        0      0     0          0    0       0     0   
1  ...    0        0        0      0     0          0    0       0     0   
2  ...    0        0        0      0     0          0    0       0     0   
3  ...    0        0        0      0     0          0    0       0     0   
4  ...    0        0        0      0     0          0    0       0     0   

   personalised  
0             0  
1             0  
2             0  
3             0  
4             0  

[5 rows x 422 columns]

<div class=h1_cell>
<p>
Now create a co-occurence matrix to represent how many times 2 words appear together in the same dataset. Multiply the occurence matrix by its transpose to get this matrix.
</div>

In [13]:
import numpy as np
comatrix = occur_matrix.T.dot(occur_matrix)
np.fill_diagonal(comatrix.values, 0)
comatrix.head()

shop  shot  show  tells  probe  ica16  leads  basilicabotanica  go  \
shop      0     0     0      0      0      0      0                 0   0   
shot      0     0     0      0      0      0      0                 0   0   
show      0     0     0      0      0      0      0                 0   0   
tells     0     0     0      0      0      0      0                 0   0   
probe     0     0     0      0      0      0      0                 0   0   

       21st  ...   hu  weekend  forever  calls  wife  sometimes  gr8  points  \
shop      0  ...    0        0        0      0     0          0    0       0   
shot      0  ...    0        0        0      0     0          0    0       0   
show      0  ...    0        0        0      0     1          0    0       0   
tells     0  ...    0        0        0      0     0          0    0       0   
probe     0  ...    0        0        0      0     0          0    0       1   

       leak  personalised  
shop      0             1  
shot      0             0  
show      0             0  
tells     0             0  
probe     1             0  

[5 rows x 422 columns]

<div class=h1_cell>
<p>
Now, this matrix is incredibly sparse, and takes up space. By decomposing this matrix with Sigular Value Decomposition, we can find the K most significant words in the dataset and get the cooccurence matrix of only those words. This significantly reduces the size of the matrix but retains the K most connected words in the data.
</div>

In [14]:
from pyspark.mllib.linalg import DenseVector
from pyspark.mllib.linalg.distributed import RowMatrix
rows = spark.sparkContext.parallelize([DenseVector(row) for row in comatrix.values.tolist()])
row_matrix = RowMatrix(rows)
svd = row_matrix.computeSVD(len(comatrix.index)/2, computeU=True)  # reduce matrix by
svd.s

DenseVector([18.3012, 15.2739, 13.173, 12.5853, 12.3664, 10.9407, 10.3887, 10.307, 10.1774, 9.6903, 9.3421, 9.1932, 9.1603, 8.7779, 8.5957, 8.1919, 8.0, 8.0, 8.0, 8.0, 8.0, 7.5983, 7.4181, 7.2364, 7.154, 7.135, 6.7001, 6.6678, 6.4699, 6.2143, 6.0, 6.0, 6.0, 5.9453, 5.6071, 5.3588, 5.2166, 5.0, 5.0, 4.9969, 4.8505, 4.7946, 4.7653, 4.5803, 4.4092, 4.0996, 4.0, 3.6114, 3.5492, 3.3857, 3.2396, 3.2168, 3.1531, 3.0895, 3.0, 3.0, 2.6778, 2.6167, 2.595, 2.5607, 2.5315, 2.4984, 2.4765, 2.4457, 2.4024, 2.3381, 2.309, 2.2449, 2.0609, 2.0, 2.0, 2.0, 2.0, 2.0, 1.986, 1.9761, 1.9371, 1.9323, 1.8883, 1.8718, 1.8434, 1.8412, 1.827, 1.8101, 1.7929, 1.7869, 1.7644, 1.7531, 1.7464, 1.7138, 1.7128, 1.6824, 1.6397, 1.6175, 1.6039, 1.5866, 1.5809, 1.5602, 1.5396, 1.5056, 1.469, 1.3127, 1.1016, 1.0448, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,

In [15]:
spark.stop()

In [16]:
subprocess.call(os.environ['SPARK_HOME'] + "/sbin/stop-all.sh")

0